# This is the configuration used to check the rubocop source code.
# For list of cops 'https://github.com/bbatsov/rubocop/tree/master/config'

require: rubocop-performance

AllCops:
  Exclude:
    - 'config/**/*'
    - 'app/main/config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/scorecard.rb'
    - 'app/models/data_set.rb'
    - 'app/models/user.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
